include: package:dart_test_tools/strict.yaml
analyzer:
plugins:
  dart_test_tools: ^7.3.3
  # jaspr_lints:
  #   version: ^0.7.2
  #   diagnostics:
  #     prefer_html_components: true
  #     sort_children_last: true
  #     styles_ordering: true
